// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v4.25.3
// source: gateway.proto

package gateway

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ENUMS
type AddressFamily int32

const (
	AddressFamily_ipv4 AddressFamily = 0
	AddressFamily_ipv6 AddressFamily = 1
)

// Enum value maps for AddressFamily.
var (
	AddressFamily_name = map[int32]string{
		0: "ipv4",
		1: "ipv6",
	}
	AddressFamily_value = map[string]int32{
		"ipv4": 0,
		"ipv6": 1,
	}
)

func (x AddressFamily) Enum() *AddressFamily {
	p := new(AddressFamily)
	*p = x
	return p
}

func (x AddressFamily) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AddressFamily) Descriptor() protoreflect.EnumDescriptor {
	return file_gateway_proto_enumTypes[0].Descriptor()
}

func (AddressFamily) Type() protoreflect.EnumType {
	return &file_gateway_proto_enumTypes[0]
}

func (x AddressFamily) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AddressFamily.Descriptor instead.
func (AddressFamily) EnumDescriptor() ([]byte, []int) {
	return file_gateway_proto_rawDescGZIP(), []int{0}
}

// REQUEST MESSAGES
type NamespaceAddReq struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	RbdPoolName       string                 `protobuf:"bytes,1,opt,name=rbd_pool_name,json=rbdPoolName,proto3" json:"rbd_pool_name,omitempty"`
	RbdImageName      string                 `protobuf:"bytes,2,opt,name=rbd_image_name,json=rbdImageName,proto3" json:"rbd_image_name,omitempty"`
	SubsystemNqn      string                 `protobuf:"bytes,3,opt,name=subsystem_nqn,json=subsystemNqn,proto3" json:"subsystem_nqn,omitempty"`
	Nsid              *uint32                `protobuf:"varint,4,opt,name=nsid,proto3,oneof" json:"nsid,omitempty"`
	BlockSize         uint32                 `protobuf:"varint,5,opt,name=block_size,json=blockSize,proto3" json:"block_size,omitempty"`
	Uuid              *string                `protobuf:"bytes,6,opt,name=uuid,proto3,oneof" json:"uuid,omitempty"`
	Anagrpid          *int32                 `protobuf:"varint,7,opt,name=anagrpid,proto3,oneof" json:"anagrpid,omitempty"`
	CreateImage       *bool                  `protobuf:"varint,8,opt,name=create_image,json=createImage,proto3,oneof" json:"create_image,omitempty"`
	Size              *uint64                `protobuf:"varint,9,opt,name=size,proto3,oneof" json:"size,omitempty"`
	Force             *bool                  `protobuf:"varint,10,opt,name=force,proto3,oneof" json:"force,omitempty"`
	NoAutoVisible     *bool                  `protobuf:"varint,11,opt,name=no_auto_visible,json=noAutoVisible,proto3,oneof" json:"no_auto_visible,omitempty"`
	TrashImage        *bool                  `protobuf:"varint,12,opt,name=trash_image,json=trashImage,proto3,oneof" json:"trash_image,omitempty"`
	DisableAutoResize *bool                  `protobuf:"varint,13,opt,name=disable_auto_resize,json=disableAutoResize,proto3,oneof" json:"disable_auto_resize,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *NamespaceAddReq) Reset() {
	*x = NamespaceAddReq{}
	mi := &file_gateway_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NamespaceAddReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NamespaceAddReq) ProtoMessage() {}

func (x *NamespaceAddReq) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NamespaceAddReq.ProtoReflect.Descriptor instead.
func (*NamespaceAddReq) Descriptor() ([]byte, []int) {
	return file_gateway_proto_rawDescGZIP(), []int{0}
}

func (x *NamespaceAddReq) GetRbdPoolName() string {
	if x != nil {
		return x.RbdPoolName
	}
	return ""
}

func (x *NamespaceAddReq) GetRbdImageName() string {
	if x != nil {
		return x.RbdImageName
	}
	return ""
}

func (x *NamespaceAddReq) GetSubsystemNqn() string {
	if x != nil {
		return x.SubsystemNqn
	}
	return ""
}

func (x *NamespaceAddReq) GetNsid() uint32 {
	if x != nil && x.Nsid != nil {
		return *x.Nsid
	}
	return 0
}

func (x *NamespaceAddReq) GetBlockSize() uint32 {
	if x != nil {
		return x.BlockSize
	}
	return 0
}

func (x *NamespaceAddReq) GetUuid() string {
	if x != nil && x.Uuid != nil {
		return *x.Uuid
	}
	return ""
}

func (x *NamespaceAddReq) GetAnagrpid() int32 {
	if x != nil && x.Anagrpid != nil {
		return *x.Anagrpid
	}
	return 0
}

func (x *NamespaceAddReq) GetCreateImage() bool {
	if x != nil && x.CreateImage != nil {
		return *x.CreateImage
	}
	return false
}

func (x *NamespaceAddReq) GetSize() uint64 {
	if x != nil && x.Size != nil {
		return *x.Size
	}
	return 0
}

func (x *NamespaceAddReq) GetForce() bool {
	if x != nil && x.Force != nil {
		return *x.Force
	}
	return false
}

func (x *NamespaceAddReq) GetNoAutoVisible() bool {
	if x != nil && x.NoAutoVisible != nil {
		return *x.NoAutoVisible
	}
	return false
}

func (x *NamespaceAddReq) GetTrashImage() bool {
	if x != nil && x.TrashImage != nil {
		return *x.TrashImage
	}
	return false
}

func (x *NamespaceAddReq) GetDisableAutoResize() bool {
	if x != nil && x.DisableAutoResize != nil {
		return *x.DisableAutoResize
	}
	return false
}

type NamespaceResizeReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SubsystemNqn  string                 `protobuf:"bytes,1,opt,name=subsystem_nqn,json=subsystemNqn,proto3" json:"subsystem_nqn,omitempty"`
	Nsid          uint32                 `protobuf:"varint,2,opt,name=nsid,proto3" json:"nsid,omitempty"`
	OBSOLETEUuid  *string                `protobuf:"bytes,3,opt,name=OBSOLETE_uuid,json=OBSOLETEUuid,proto3,oneof" json:"OBSOLETE_uuid,omitempty"`
	NewSize       uint64                 `protobuf:"varint,4,opt,name=new_size,json=newSize,proto3" json:"new_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NamespaceResizeReq) Reset() {
	*x = NamespaceResizeReq{}
	mi := &file_gateway_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NamespaceResizeReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NamespaceResizeReq) ProtoMessage() {}

func (x *NamespaceResizeReq) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NamespaceResizeReq.ProtoReflect.Descriptor instead.
func (*NamespaceResizeReq) Descriptor() ([]byte, []int) {
	return file_gateway_proto_rawDescGZIP(), []int{1}
}

func (x *NamespaceResizeReq) GetSubsystemNqn() string {
	if x != nil {
		return x.SubsystemNqn
	}
	return ""
}

func (x *NamespaceResizeReq) GetNsid() uint32 {
	if x != nil {
		return x.Nsid
	}
	return 0
}

func (x *NamespaceResizeReq) GetOBSOLETEUuid() string {
	if x != nil && x.OBSOLETEUuid != nil {
		return *x.OBSOLETEUuid
	}
	return ""
}

func (x *NamespaceResizeReq) GetNewSize() uint64 {
	if x != nil {
		return x.NewSize
	}
	return 0
}

type NamespaceDeleteReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SubsystemNqn  string                 `protobuf:"bytes,1,opt,name=subsystem_nqn,json=subsystemNqn,proto3" json:"subsystem_nqn,omitempty"`
	Nsid          uint32                 `protobuf:"varint,2,opt,name=nsid,proto3" json:"nsid,omitempty"`
	OBSOLETEUuid  *string                `protobuf:"bytes,3,opt,name=OBSOLETE_uuid,json=OBSOLETEUuid,proto3,oneof" json:"OBSOLETE_uuid,omitempty"`
	IAmSure       *bool                  `protobuf:"varint,4,opt,name=i_am_sure,json=iAmSure,proto3,oneof" json:"i_am_sure,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NamespaceDeleteReq) Reset() {
	*x = NamespaceDeleteReq{}
	mi := &file_gateway_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NamespaceDeleteReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NamespaceDeleteReq) ProtoMessage() {}

func (x *NamespaceDeleteReq) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NamespaceDeleteReq.ProtoReflect.Descriptor instead.
func (*NamespaceDeleteReq) Descriptor() ([]byte, []int) {
	return file_gateway_proto_rawDescGZIP(), []int{2}
}

func (x *NamespaceDeleteReq) GetSubsystemNqn() string {
	if x != nil {
		return x.SubsystemNqn
	}
	return ""
}

func (x *NamespaceDeleteReq) GetNsid() uint32 {
	if x != nil {
		return x.Nsid
	}
	return 0
}

func (x *NamespaceDeleteReq) GetOBSOLETEUuid() string {
	if x != nil && x.OBSOLETEUuid != nil {
		return *x.OBSOLETEUuid
	}
	return ""
}

func (x *NamespaceDeleteReq) GetIAmSure() bool {
	if x != nil && x.IAmSure != nil {
		return *x.IAmSure
	}
	return false
}

type ListNamespacesReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Subsystem     string                 `protobuf:"bytes,1,opt,name=subsystem,proto3" json:"subsystem,omitempty"`
	Nsid          *uint32                `protobuf:"varint,2,opt,name=nsid,proto3,oneof" json:"nsid,omitempty"`
	Uuid          *string                `protobuf:"bytes,3,opt,name=uuid,proto3,oneof" json:"uuid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListNamespacesReq) Reset() {
	*x = ListNamespacesReq{}
	mi := &file_gateway_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListNamespacesReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListNamespacesReq) ProtoMessage() {}

func (x *ListNamespacesReq) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListNamespacesReq.ProtoReflect.Descriptor instead.
func (*ListNamespacesReq) Descriptor() ([]byte, []int) {
	return file_gateway_proto_rawDescGZIP(), []int{3}
}

func (x *ListNamespacesReq) GetSubsystem() string {
	if x != nil {
		return x.Subsystem
	}
	return ""
}

func (x *ListNamespacesReq) GetNsid() uint32 {
	if x != nil && x.Nsid != nil {
		return *x.Nsid
	}
	return 0
}

func (x *ListNamespacesReq) GetUuid() string {
	if x != nil && x.Uuid != nil {
		return *x.Uuid
	}
	return ""
}

// RESPONSE MESSAGES
type ReqStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        int32                  `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReqStatus) Reset() {
	*x = ReqStatus{}
	mi := &file_gateway_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReqStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqStatus) ProtoMessage() {}

func (x *ReqStatus) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqStatus.ProtoReflect.Descriptor instead.
func (*ReqStatus) Descriptor() ([]byte, []int) {
	return file_gateway_proto_rawDescGZIP(), []int{4}
}

func (x *ReqStatus) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *ReqStatus) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

type NsidStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        int32                  `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	Nsid          uint32                 `protobuf:"varint,3,opt,name=nsid,proto3" json:"nsid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NsidStatus) Reset() {
	*x = NsidStatus{}
	mi := &file_gateway_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NsidStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NsidStatus) ProtoMessage() {}

func (x *NsidStatus) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NsidStatus.ProtoReflect.Descriptor instead.
func (*NsidStatus) Descriptor() ([]byte, []int) {
	return file_gateway_proto_rawDescGZIP(), []int{5}
}

func (x *NsidStatus) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *NsidStatus) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *NsidStatus) GetNsid() uint32 {
	if x != nil {
		return x.Nsid
	}
	return 0
}

type NamespaceCli struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Nsid               uint32                 `protobuf:"varint,1,opt,name=nsid,proto3" json:"nsid,omitempty"`
	BdevName           string                 `protobuf:"bytes,2,opt,name=bdev_name,json=bdevName,proto3" json:"bdev_name,omitempty"`
	RbdImageName       string                 `protobuf:"bytes,3,opt,name=rbd_image_name,json=rbdImageName,proto3" json:"rbd_image_name,omitempty"`
	RbdPoolName        string                 `protobuf:"bytes,4,opt,name=rbd_pool_name,json=rbdPoolName,proto3" json:"rbd_pool_name,omitempty"`
	LoadBalancingGroup uint32                 `protobuf:"varint,5,opt,name=load_balancing_group,json=loadBalancingGroup,proto3" json:"load_balancing_group,omitempty"`
	BlockSize          uint32                 `protobuf:"varint,6,opt,name=block_size,json=blockSize,proto3" json:"block_size,omitempty"`
	RbdImageSize       uint64                 `protobuf:"varint,7,opt,name=rbd_image_size,json=rbdImageSize,proto3" json:"rbd_image_size,omitempty"`
	Uuid               string                 `protobuf:"bytes,8,opt,name=uuid,proto3" json:"uuid,omitempty"`
	RwIosPerSecond     uint64                 `protobuf:"varint,9,opt,name=rw_ios_per_second,json=rwIosPerSecond,proto3" json:"rw_ios_per_second,omitempty"`
	RwMbytesPerSecond  uint64                 `protobuf:"varint,10,opt,name=rw_mbytes_per_second,json=rwMbytesPerSecond,proto3" json:"rw_mbytes_per_second,omitempty"`
	RMbytesPerSecond   uint64                 `protobuf:"varint,11,opt,name=r_mbytes_per_second,json=rMbytesPerSecond,proto3" json:"r_mbytes_per_second,omitempty"`
	WMbytesPerSecond   uint64                 `protobuf:"varint,12,opt,name=w_mbytes_per_second,json=wMbytesPerSecond,proto3" json:"w_mbytes_per_second,omitempty"`
	AutoVisible        bool                   `protobuf:"varint,13,opt,name=auto_visible,json=autoVisible,proto3" json:"auto_visible,omitempty"`
	Hosts              []string               `protobuf:"bytes,14,rep,name=hosts,proto3" json:"hosts,omitempty"`
	NsSubsystemNqn     *string                `protobuf:"bytes,15,opt,name=ns_subsystem_nqn,json=nsSubsystemNqn,proto3,oneof" json:"ns_subsystem_nqn,omitempty"`
	TrashImage         *bool                  `protobuf:"varint,16,opt,name=trash_image,json=trashImage,proto3,oneof" json:"trash_image,omitempty"`
	DisableAutoResize  *bool                  `protobuf:"varint,17,opt,name=disable_auto_resize,json=disableAutoResize,proto3,oneof" json:"disable_auto_resize,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *NamespaceCli) Reset() {
	*x = NamespaceCli{}
	mi := &file_gateway_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NamespaceCli) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NamespaceCli) ProtoMessage() {}

func (x *NamespaceCli) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NamespaceCli.ProtoReflect.Descriptor instead.
func (*NamespaceCli) Descriptor() ([]byte, []int) {
	return file_gateway_proto_rawDescGZIP(), []int{6}
}

func (x *NamespaceCli) GetNsid() uint32 {
	if x != nil {
		return x.Nsid
	}
	return 0
}

func (x *NamespaceCli) GetBdevName() string {
	if x != nil {
		return x.BdevName
	}
	return ""
}

func (x *NamespaceCli) GetRbdImageName() string {
	if x != nil {
		return x.RbdImageName
	}
	return ""
}

func (x *NamespaceCli) GetRbdPoolName() string {
	if x != nil {
		return x.RbdPoolName
	}
	return ""
}

func (x *NamespaceCli) GetLoadBalancingGroup() uint32 {
	if x != nil {
		return x.LoadBalancingGroup
	}
	return 0
}

func (x *NamespaceCli) GetBlockSize() uint32 {
	if x != nil {
		return x.BlockSize
	}
	return 0
}

func (x *NamespaceCli) GetRbdImageSize() uint64 {
	if x != nil {
		return x.RbdImageSize
	}
	return 0
}

func (x *NamespaceCli) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *NamespaceCli) GetRwIosPerSecond() uint64 {
	if x != nil {
		return x.RwIosPerSecond
	}
	return 0
}

func (x *NamespaceCli) GetRwMbytesPerSecond() uint64 {
	if x != nil {
		return x.RwMbytesPerSecond
	}
	return 0
}

func (x *NamespaceCli) GetRMbytesPerSecond() uint64 {
	if x != nil {
		return x.RMbytesPerSecond
	}
	return 0
}

func (x *NamespaceCli) GetWMbytesPerSecond() uint64 {
	if x != nil {
		return x.WMbytesPerSecond
	}
	return 0
}

func (x *NamespaceCli) GetAutoVisible() bool {
	if x != nil {
		return x.AutoVisible
	}
	return false
}

func (x *NamespaceCli) GetHosts() []string {
	if x != nil {
		return x.Hosts
	}
	return nil
}

func (x *NamespaceCli) GetNsSubsystemNqn() string {
	if x != nil && x.NsSubsystemNqn != nil {
		return *x.NsSubsystemNqn
	}
	return ""
}

func (x *NamespaceCli) GetTrashImage() bool {
	if x != nil && x.TrashImage != nil {
		return *x.TrashImage
	}
	return false
}

func (x *NamespaceCli) GetDisableAutoResize() bool {
	if x != nil && x.DisableAutoResize != nil {
		return *x.DisableAutoResize
	}
	return false
}

type NamespacesInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        int32                  `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	SubsystemNqn  string                 `protobuf:"bytes,3,opt,name=subsystem_nqn,json=subsystemNqn,proto3" json:"subsystem_nqn,omitempty"`
	Namespaces    []*NamespaceCli        `protobuf:"bytes,4,rep,name=namespaces,proto3" json:"namespaces,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NamespacesInfo) Reset() {
	*x = NamespacesInfo{}
	mi := &file_gateway_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NamespacesInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NamespacesInfo) ProtoMessage() {}

func (x *NamespacesInfo) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NamespacesInfo.ProtoReflect.Descriptor instead.
func (*NamespacesInfo) Descriptor() ([]byte, []int) {
	return file_gateway_proto_rawDescGZIP(), []int{7}
}

func (x *NamespacesInfo) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *NamespacesInfo) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *NamespacesInfo) GetSubsystemNqn() string {
	if x != nil {
		return x.SubsystemNqn
	}
	return ""
}

func (x *NamespacesInfo) GetNamespaces() []*NamespaceCli {
	if x != nil {
		return x.Namespaces
	}
	return nil
}

var File_gateway_proto protoreflect.FileDescriptor

const file_gateway_proto_rawDesc = "" +
	"\n" +
	"\rgateway.proto\x12\agateway\"\xd7\x04\n" +
	"\x11namespace_add_req\x12\"\n" +
	"\rrbd_pool_name\x18\x01 \x01(\tR\vrbdPoolName\x12$\n" +
	"\x0erbd_image_name\x18\x02 \x01(\tR\frbdImageName\x12#\n" +
	"\rsubsystem_nqn\x18\x03 \x01(\tR\fsubsystemNqn\x12\x17\n" +
	"\x04nsid\x18\x04 \x01(\rH\x00R\x04nsid\x88\x01\x01\x12\x1d\n" +
	"\n" +
	"block_size\x18\x05 \x01(\rR\tblockSize\x12\x17\n" +
	"\x04uuid\x18\x06 \x01(\tH\x01R\x04uuid\x88\x01\x01\x12\x1f\n" +
	"\banagrpid\x18\a \x01(\x05H\x02R\banagrpid\x88\x01\x01\x12&\n" +
	"\fcreate_image\x18\b \x01(\bH\x03R\vcreateImage\x88\x01\x01\x12\x17\n" +
	"\x04size\x18\t \x01(\x04H\x04R\x04size\x88\x01\x01\x12\x19\n" +
	"\x05force\x18\n" +
	" \x01(\bH\x05R\x05force\x88\x01\x01\x12+\n" +
	"\x0fno_auto_visible\x18\v \x01(\bH\x06R\rnoAutoVisible\x88\x01\x01\x12$\n" +
	"\vtrash_image\x18\f \x01(\bH\aR\n" +
	"trashImage\x88\x01\x01\x123\n" +
	"\x13disable_auto_resize\x18\r \x01(\bH\bR\x11disableAutoResize\x88\x01\x01B\a\n" +
	"\x05_nsidB\a\n" +
	"\x05_uuidB\v\n" +
	"\t_anagrpidB\x0f\n" +
	"\r_create_imageB\a\n" +
	"\x05_sizeB\b\n" +
	"\x06_forceB\x12\n" +
	"\x10_no_auto_visibleB\x0e\n" +
	"\f_trash_imageB\x16\n" +
	"\x14_disable_auto_resize\"\xa6\x01\n" +
	"\x14namespace_resize_req\x12#\n" +
	"\rsubsystem_nqn\x18\x01 \x01(\tR\fsubsystemNqn\x12\x12\n" +
	"\x04nsid\x18\x02 \x01(\rR\x04nsid\x12(\n" +
	"\rOBSOLETE_uuid\x18\x03 \x01(\tH\x00R\fOBSOLETEUuid\x88\x01\x01\x12\x19\n" +
	"\bnew_size\x18\x04 \x01(\x04R\anewSizeB\x10\n" +
	"\x0e_OBSOLETE_uuid\"\xba\x01\n" +
	"\x14namespace_delete_req\x12#\n" +
	"\rsubsystem_nqn\x18\x01 \x01(\tR\fsubsystemNqn\x12\x12\n" +
	"\x04nsid\x18\x02 \x01(\rR\x04nsid\x12(\n" +
	"\rOBSOLETE_uuid\x18\x03 \x01(\tH\x00R\fOBSOLETEUuid\x88\x01\x01\x12\x1f\n" +
	"\ti_am_sure\x18\x04 \x01(\bH\x01R\aiAmSure\x88\x01\x01B\x10\n" +
	"\x0e_OBSOLETE_uuidB\f\n" +
	"\n" +
	"_i_am_sure\"w\n" +
	"\x13list_namespaces_req\x12\x1c\n" +
	"\tsubsystem\x18\x01 \x01(\tR\tsubsystem\x12\x17\n" +
	"\x04nsid\x18\x02 \x01(\rH\x00R\x04nsid\x88\x01\x01\x12\x17\n" +
	"\x04uuid\x18\x03 \x01(\tH\x01R\x04uuid\x88\x01\x01B\a\n" +
	"\x05_nsidB\a\n" +
	"\x05_uuid\"I\n" +
	"\n" +
	"req_status\x12\x16\n" +
	"\x06status\x18\x01 \x01(\x05R\x06status\x12#\n" +
	"\rerror_message\x18\x02 \x01(\tR\ferrorMessage\"^\n" +
	"\vnsid_status\x12\x16\n" +
	"\x06status\x18\x01 \x01(\x05R\x06status\x12#\n" +
	"\rerror_message\x18\x02 \x01(\tR\ferrorMessage\x12\x12\n" +
	"\x04nsid\x18\x03 \x01(\rR\x04nsid\"\xcf\x05\n" +
	"\rnamespace_cli\x12\x12\n" +
	"\x04nsid\x18\x01 \x01(\rR\x04nsid\x12\x1b\n" +
	"\tbdev_name\x18\x02 \x01(\tR\bbdevName\x12$\n" +
	"\x0erbd_image_name\x18\x03 \x01(\tR\frbdImageName\x12\"\n" +
	"\rrbd_pool_name\x18\x04 \x01(\tR\vrbdPoolName\x120\n" +
	"\x14load_balancing_group\x18\x05 \x01(\rR\x12loadBalancingGroup\x12\x1d\n" +
	"\n" +
	"block_size\x18\x06 \x01(\rR\tblockSize\x12$\n" +
	"\x0erbd_image_size\x18\a \x01(\x04R\frbdImageSize\x12\x12\n" +
	"\x04uuid\x18\b \x01(\tR\x04uuid\x12)\n" +
	"\x11rw_ios_per_second\x18\t \x01(\x04R\x0erwIosPerSecond\x12/\n" +
	"\x14rw_mbytes_per_second\x18\n" +
	" \x01(\x04R\x11rwMbytesPerSecond\x12-\n" +
	"\x13r_mbytes_per_second\x18\v \x01(\x04R\x10rMbytesPerSecond\x12-\n" +
	"\x13w_mbytes_per_second\x18\f \x01(\x04R\x10wMbytesPerSecond\x12!\n" +
	"\fauto_visible\x18\r \x01(\bR\vautoVisible\x12\x14\n" +
	"\x05hosts\x18\x0e \x03(\tR\x05hosts\x12-\n" +
	"\x10ns_subsystem_nqn\x18\x0f \x01(\tH\x00R\x0ensSubsystemNqn\x88\x01\x01\x12$\n" +
	"\vtrash_image\x18\x10 \x01(\bH\x01R\n" +
	"trashImage\x88\x01\x01\x123\n" +
	"\x13disable_auto_resize\x18\x11 \x01(\bH\x02R\x11disableAutoResize\x88\x01\x01B\x13\n" +
	"\x11_ns_subsystem_nqnB\x0e\n" +
	"\f_trash_imageB\x16\n" +
	"\x14_disable_auto_resize\"\xab\x01\n" +
	"\x0fnamespaces_info\x12\x16\n" +
	"\x06status\x18\x01 \x01(\x05R\x06status\x12#\n" +
	"\rerror_message\x18\x02 \x01(\tR\ferrorMessage\x12#\n" +
	"\rsubsystem_nqn\x18\x03 \x01(\tR\fsubsystemNqn\x126\n" +
	"\n" +
	"namespaces\x18\x04 \x03(\v2\x16.gateway.namespace_cliR\n" +
	"namespaces*#\n" +
	"\rAddressFamily\x12\b\n" +
	"\x04ipv4\x10\x00\x12\b\n" +
	"\x04ipv6\x10\x012\xaf\x02\n" +
	"\aGateway\x12C\n" +
	"\rnamespace_add\x12\x1a.gateway.namespace_add_req\x1a\x14.gateway.nsid_status\"\x00\x12H\n" +
	"\x10namespace_resize\x12\x1d.gateway.namespace_resize_req\x1a\x13.gateway.req_status\"\x00\x12H\n" +
	"\x10namespace_delete\x12\x1d.gateway.namespace_delete_req\x1a\x13.gateway.req_status\"\x00\x12K\n" +
	"\x0flist_namespaces\x12\x1c.gateway.list_namespaces_req\x1a\x18.gateway.namespaces_info\"\x00B6Z4github.com/gadididi/nvmeof-csi/proto/gateway;gatewayb\x06proto3"

var (
	file_gateway_proto_rawDescOnce sync.Once
	file_gateway_proto_rawDescData []byte
)

func file_gateway_proto_rawDescGZIP() []byte {
	file_gateway_proto_rawDescOnce.Do(func() {
		file_gateway_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_gateway_proto_rawDesc), len(file_gateway_proto_rawDesc)))
	})
	return file_gateway_proto_rawDescData
}

var file_gateway_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_gateway_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_gateway_proto_goTypes = []any{
	(AddressFamily)(0),         // 0: gateway.AddressFamily
	(*NamespaceAddReq)(nil),    // 1: gateway.namespace_add_req
	(*NamespaceResizeReq)(nil), // 2: gateway.namespace_resize_req
	(*NamespaceDeleteReq)(nil), // 3: gateway.namespace_delete_req
	(*ListNamespacesReq)(nil),  // 4: gateway.list_namespaces_req
	(*ReqStatus)(nil),          // 5: gateway.req_status
	(*NsidStatus)(nil),         // 6: gateway.nsid_status
	(*NamespaceCli)(nil),       // 7: gateway.namespace_cli
	(*NamespacesInfo)(nil),     // 8: gateway.namespaces_info
}
var file_gateway_proto_depIdxs = []int32{
	7, // 0: gateway.namespaces_info.namespaces:type_name -> gateway.namespace_cli
	1, // 1: gateway.Gateway.namespace_add:input_type -> gateway.namespace_add_req
	2, // 2: gateway.Gateway.namespace_resize:input_type -> gateway.namespace_resize_req
	3, // 3: gateway.Gateway.namespace_delete:input_type -> gateway.namespace_delete_req
	4, // 4: gateway.Gateway.list_namespaces:input_type -> gateway.list_namespaces_req
	6, // 5: gateway.Gateway.namespace_add:output_type -> gateway.nsid_status
	5, // 6: gateway.Gateway.namespace_resize:output_type -> gateway.req_status
	5, // 7: gateway.Gateway.namespace_delete:output_type -> gateway.req_status
	8, // 8: gateway.Gateway.list_namespaces:output_type -> gateway.namespaces_info
	5, // [5:9] is the sub-list for method output_type
	1, // [1:5] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_gateway_proto_init() }
func file_gateway_proto_init() {
	if File_gateway_proto != nil {
		return
	}
	file_gateway_proto_msgTypes[0].OneofWrappers = []any{}
	file_gateway_proto_msgTypes[1].OneofWrappers = []any{}
	file_gateway_proto_msgTypes[2].OneofWrappers = []any{}
	file_gateway_proto_msgTypes[3].OneofWrappers = []any{}
	file_gateway_proto_msgTypes[6].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_gateway_proto_rawDesc), len(file_gateway_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_gateway_proto_goTypes,
		DependencyIndexes: file_gateway_proto_depIdxs,
		EnumInfos:         file_gateway_proto_enumTypes,
		MessageInfos:      file_gateway_proto_msgTypes,
	}.Build()
	File_gateway_proto = out.File
	file_gateway_proto_goTypes = nil
	file_gateway_proto_depIdxs = nil
}
