# SPDX-License-Identifier: Apache-2.0
# Copyright (c) Arm Limited and Contributors
# Copyright (c) Intel Corporation
---
kind: StatefulSet
apiVersion: apps/v1
metadata:
  name:  nvmeof-csi-controller
spec:
  serviceName: nvmeof-csi-controller
  replicas: 1
  selector:
    matchLabels:
      app: nvmeof-csi-controller
  template:
    metadata:
      labels:
        app: nvmeof-csi-controller
    spec:
      serviceAccount: nvmeof-csi-controller-sa
      hostNetwork: true
      containers:
      - name: csi-provisioner
        image: registry.k8s.io/sig-storage/csi-provisioner:v3.5.0
        imagePullPolicy: "IfNotPresent"
        args:
        - "--v=5"
        - "--csi-address=unix:///csi/csi-provisioner.sock"
        - "--timeout=30s"
        - "--retry-interval-start=500ms"
        - "--leader-election=true"
        volumeMounts:
        - name: socket-dir
          mountPath: /csi
      - name: nvmeof-csi
        image: quay.io/gdidi/nvmeof-csi:latest
        imagePullPolicy: "IfNotPresent"
        args:
        - "--v=5"
        - "--endpoint=unix:///csi/csi-provisioner.sock"
        - "--nodeid=$(NODE_ID)"
        - "--controller"
        env:
        - name: NODE_ID
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        volumeMounts:
        - name: socket-dir
          mountPath: /csi
        - name: nvmeof-csi-config
          mountPath: /etc/nvmeof-csi-config/
          readOnly: true
      volumes:
      - name: socket-dir
        emptyDir:
          medium: "Memory"
      - name: nvmeof-csi-config
        configMap:
          name: nvmeof-csi-config
