# SPDX-License-Identifier: Apache-2.0
# Copyright (c) Arm Limited and Contributors
# Copyright (c) Intel Corporation
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: nvmeof-csi-sc
provisioner: csi.nvmeof.io
parameters:
  fsType: ext4
reclaimPolicy: Delete
volumeBindingMode: Immediate
