# SPDX-License-Identifier: Apache-2.0
# Copyright (c) Arm Limited and Contributors
# Copyright (c) Intel Corporation
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: nvmeof-csi-sc
provisioner: csi.nvmeof.io
parameters:
  fsType: ext4
  RbdPoolName: "mypool"
  SubsystemNqn: "nqn.2016-06.io.spdk:cnode1.mygroup1"
  traddr: "10.242.64.32"
  trsvcid: "4420"
  transport: "tcp"
reclaimPolicy: Delete
volumeBindingMode: Immediate
